### ISSUE TITLE
ERROR WHEN JOINING

### ISSUE THREAD

**Issue by blackstormlab** [TomGrobbe/vBasic#3]
![capture](https://user-images.githubusercontent.com/35038928/34492421-cc289fc8-efe7-11e7-93f0-64b0645df27b.PNG)

**Comment by TomGrobbe** [comment]
Is this on your own server? If so, try restarting it (without clearing the cache) and restart your client. Then try to rejoin.

**Comment by ngschaider** [comment]
I also experience this error just after completing the Installation.

Things I have tried and did not solve the issue:
1. Restarting Server
2. Restarting Client
3. Clearing Client Cache

**Comment by blackstormlab** [comment]
fixed it when unzipping it made a folder in a folder now it's working @Swapy97 also don't forget to rename the folder to just vBasic
and thx for the quick reply @TomGrobbe

**Comment by ngschaider** [comment]
@StinkyTACO Wow, i cant believe that i missed that.
Now I'm getting the startup message, that I successfully set up all convars but I'm still getting the same error on the client. 

I also tried restarting Server and Client, and clearing client cache again.

**Comment by blackstormlab** [comment]
do you have Teamviewer? also here is my discord https://discord.gg/pc8q7C

**Comment by ngschaider** [comment]
I got my problem resolved by deleting the server cache and restarting the server.
